### ISSUE TITLE
Uninstall command not working

### ISSUE THREAD

**Issue by Listless-Winter** [ILOVEPIE/HDRDeck#3]
Hi, First of all thank you very much for this script ^^ , I've been using this script for a few months and it works on some of my games and some games have weird color saturations but it seems that HDR support has been added in steamOS 3.5 and I am trying to uninstall this but the hdrdeck_uninstall command cannot be found. I tried to reinstall the script and it seems that there is an error when adding the uninstall command like it cannot find the directory. I'm fairly new in Linux so I dont know how to fix this. 

I don't mind not uninstalling this if this will not cause a problem to hdr when steamOS 3.5 is out.

**Comment by ILOVEPIE** [comment]
Try uninstalling with rwfus -rR and see if it works.

**Comment by Listless-Winter** [comment]
I've managed to get the hdrdeck_uninstall by doing rwfus -rR and reinstalling this script again, but i still cant use the hdrdeck_uninstall command so i have to manually find its script and execute it. After rebooting, it seems that hdr is still enabled.

**Comment by ILOVEPIE** [comment]
don't reinstall just use rwfus -rR and reboot

**Comment by Listless-Winter** [comment]
Thank you!! It works. The first time i used rwfus -rR and rebooted, it didn't work thats why i tried to reinstall it. I used rwfus -rR again and now hdr is disabled for my games.
